# Generated by Django 3.2.5 on 2021-09-06 12:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tasktytle', models.CharField(max_length=50)),
                ('TaskDe', models.TextField()),
                ('TaskDate', models.DateField(default=datetime.date(2021, 9, 6))),
            ],
        ),
    ]
