# Generated by Django 3.2.5 on 2021-09-09 16:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='TaskDate',
            field=models.DateField(default=datetime.date(2021, 9, 9)),
        ),
    ]
