# Generated by Django 3.2.5 on 2021-09-11 15:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_alter_task_taskdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='task2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasktitle', models.CharField(max_length=50)),
                ('taskdes', models.TextField()),
                ('taskdate', models.DateField(default=datetime.date(2021, 9, 11))),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='TaskDate',
            field=models.DateField(default=datetime.date(2021, 9, 11)),
        ),
    ]
